### ISSUE TITLE
Have you created a new host?

### ISSUE THREAD

**Issue by gallegonovato** [Zelo72/hosts#3]
Good afternoon:

Reviewing your host files. I noticed
  https://github.com/Zelo72/hosts/blob/main/doh-vpn-proxy-bypass.txt

https://github.com/Zelo72/hosts/blob/main/kees1958.txt

https://github.com/Zelo72/hosts/blob/main/personal.txt

This last one is included in the big. But you recommend me to use the other ones together with your other three that you recommended me.

Thanks for your help and time.

**Comment by Zelo72** [comment]
The list of kees is included in my lists, as mentioned in the README. If you use the list generated for you, then the DoH list is also included.

See the sources for your list:
https://github.com/Zelo72/rpi/blob/master/pihole/blocklists/build/gallegonovato/gallegonovato.config.sourcelists

Your list:
https://raw.githubusercontent.com/Zelo72/rpi/master/pihole/blocklists/build/gallegonovato/out/gallegonovato.hosts
