### ISSUE TITLE
Removal request - ||linkprotect.cudasvc.com^

### ISSUE THREAD

**Issue by gyCfjSnO** [Zelo72/hosts#4]
```||linkprotect.cudasvc.com^``` incorrectly blocked on the Threat Intelligence Feeds, domain is part of the Barracuda Email Security Service.

The blocked domain is documented here https://campus.barracuda.com/product/essentials/doc/49055519/understanding-link-protection/

**Comment by Zelo72** [comment]
Hello @gyCfjSnO, thank you for the report. The domain has been removed.
